# Generated by Django 3.2.7 on 2021-09-22 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('article_id', models.BigAutoField(max_length=6, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('abstract', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=100)),
                ('domain', models.CharField(max_length=100)),
                ('concept', models.CharField(max_length=100)),
                ('doi', models.CharField(blank=True, max_length=100, null=True)),
                ('image', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
