# Generated by Django 3.2.7 on 2021-09-23 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeletter', '0001_initial'),
    ]

    operations = [
    ]
