# Generated by Django 3.2.7 on 2021-09-23 02:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('codeletter', '0003_auto_20210922_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentArticle',
            fields=[
                ('sent_article_id', models.AutoField(primary_key=True, serialize=False)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('read_flag', models.BooleanField(default=False)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeletter.article')),
                ('concept_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeletter.concept')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
